micronaut:
  application:
    name: parkingToApi

info:
  version: ${project.version}

endpoints:
  health:
    sensitive: false
    details-visible: anonymous
  info:
    sensitive: false
  env:
    sensitive: false
  beans:
    sensitive: false