POST http://localhost:8080/api/ingestion
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.csv"

< /Users/robyndalgleish/Downloads/garbage_parking.csv
--WebAppBoundary--

###